<?php
/**
 * @file
 * Debut import module.
 */

// Define variables for importer.
define('DEBUT_IMPORT_NEWS_IMPORTER', 'debut_news_importer');
define('DEBUT_IMPORT_DOCUMENTS_IMPORTER', 'debut_documents_importer');
define('DEBUT_IMPORT_PRESS_IMPORTER', 'debut_press_importer');
define('DEBUT_IMPORT_VIDEO_IMPORTER', 'debut_video_importer');
define('DEBUT_IMPORT_PHOTO_IMPORTER', 'debut_photo_reports_importer');
define('DEBUT_IMPORT_TRAVELS_DESCRIPTION_IMPORTER', 'debut_travels_description_importer');
define('DEBUT_IMPORT_TRAVELS_IMPORTER', 'debut_travels_importer');
define('DEBUT_IMPORT_MC_TEXT_IMPORTER', 'debut_master_class_text_importer');

define('DEBUT_IMPORT_SOURCE_MEDIA_PATH', 'public://import/');

// Define default import lng.
define('DEBUT_IMPORT_DEFAULT_LNG', variable_get('DEBUT_IMPORT_DEFAULT_LNG', 'ru'));

module_load_include('inc', 'debut_import');

/**
 * Implements hook_feeds_after_parse().
 */
function debut_import_feeds_after_parse(FeedsSource $source, FeedsParserResult $result) {

  // Check if we on Debut imports.
  if (!debut_import_import_id_check($source)) {
    return;
  }

  // Update parsed results.
  switch ($source->importer->id) {
    case DEBUT_IMPORT_VIDEO_IMPORTER:
    case DEBUT_IMPORT_PHOTO_IMPORTER:
      debut_import_update_filepath($result);
      break;
  }

  switch ($source->importer->id) {
    default:
      break;
  }
}

/**
 * Implements hook_feeds_presave().
 */
function debut_import_feeds_presave(FeedsSource $source, $entity, $item) {

  // Check if we on Debut imports.
  if (!debut_import_import_id_check($source)) {
    return;
  }

  switch ($source->importer->id) {
    case DEBUT_IMPORT_NEWS_IMPORTER:
    case DEBUT_IMPORT_DOCUMENTS_IMPORTER:
    case DEBUT_IMPORT_PRESS_IMPORTER:
    case DEBUT_IMPORT_VIDEO_IMPORTER:
    case DEBUT_IMPORT_TRAVELS_DESCRIPTION_IMPORTER:
    case DEBUT_IMPORT_TRAVELS_IMPORTER:
      debut_import_set_publication_date($source, $entity, $item);
      break;

    case DEBUT_IMPORT_PHOTO_IMPORTER:
      debut_import_photo_import_actions($source, $entity, $item);
      break;
    default:
      break;
  }

  $entity->language = DEBUT_IMPORT_DEFAULT_LNG;
}
