<?php
/**
 * @file
 * Module hooks.
 */

define('QTOOLS_VIEWS_MODE_FIELDS', 1);
define('QTOOLS_VIEWS_MODE_PREVIEW', 2);
define('QTOOLS_TAG_EQUAL_SIGN', variable_get('QTOOLS_TAG_EQUAL_SIGN', '|'));

// Save Cookie state as they were in request, this is required to check
// if we allowed to redirect.
$GLOBAL['qtools_request_cookie'] = $_COOKIE;

// Loading base api set.
module_load_include('inc', 'qtools');